---
name: Build Release APK
on:
  workflow_dispatch:
    branches:
      - deepLX-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: deepLX-test
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Install yasm
        run: sudo apt install -y yasm
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          target-level: 34
          build-tools: 34.0.0
          ndk: 25.2.9519653
      - name: Cache native dependencies
        id: cache-native
        uses: actions/cache@v4
        with:
          path: |
            TMessagesProj/jni/ffmpeg/build
            TMessagesProj/jni/libvpx/build
            TMessagesProj/jni/boringssl/build
          key: native-${{ hashFiles('TMessagesProj/jni/**',
            'TMessagesProj/jni/*ffmpeg*.sh', 'TMessagesProj/jni/*libvpx*.sh',
            'TMessagesProj/jni/patches/ffmpeg/*',
            'TMessagesProj/jni/boringssl/**') }}
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
      - name: Build native dependencies
        if: steps.cache-native.outputs.cache-hit != 'true'
        run: |
          ./run init libs
          ./run libs update
      - name: Create local.properties
        run: >
          echo "sdk.dir=${ANDROID_HOME}" >> local.properties

          echo "TELEGRAM_APP_ID=${{ secrets.TELEGRAM_APP_ID }}" >> local.properties

          echo "TELEGRAM_APP_HASH=${{ secrets.TELEGRAM_APP_HASH }}" >> local.properties

          echo "ALIAS_NAME=${{ secrets.ALIAS_NAME }}" >> local.properties

          echo "KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }}" >> local.properties

          echo "ALIAS_PASS=${{ secrets.ALIAS_PASS }}" >> local.properties
      - name: Decode and place keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Release APK
        run: ./gradlew assembleRelease
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: TMessagesProj/build/outputs/apk/release/*.apk
          retention-days: 7
